production: &production
  adapter: redis
  url: redis://redistogo:bed731f7ab1b6e64c0b3109ab6ba61de@barreleye.redistogo.com:11371/
development: &development
  adapter: redis
  url: redis://localhost:6379
test: *development
